# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My jekyll Blog
email: pramod.rh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi this is Pramod Web Designer and Developer.
baseurl: "/jekyll-blog" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ppramodrh
github_username:  pramodrhegde

permalink: /:categories/:title

links:
 - title: about
   url: /about
 - title: work
   url: /work
 - title: articles
   url: /articles
 - title: hire-me
   url: /hire-me

# Build settings
markdown: kramdown
